- openssl1x/Patches/0007-CVE-2020-1968.patch
- openssl1x/Patches/0008-CVE-2020-1971.patch
Seems to compile okay, but will need some smoke-testing.  NOTE:  Eliminates RC4 and 3DES as supported.
> OS-8252 Patch illumos-extra openssl for two CVEs

- gnupg/Patches/0002-OS-8313-do-not-check.patch
This is "solution 1" where we just get rid of running the post-compile checks.  It is not wonderful, but it may get us over the can't-build-smartos-live hump.
> OS-8313 Addition of memrchr breaks illumos-extra gnupg build

- openssl1x/Patches/0013-CVE-2021-3712.patch
- openssl1x/sunw_prefix.h
Needs testing, builds successfully at least insofar as not holding up the rest of 0-extra-stamp.
> OS-8314 Address CVE-2021-3712 for OpenSSL 1.0.2 in illumos-extra

- openssh/Patches/0033-CVE-2021-41617.patch
Testing so far:  Modified locally built smartos-live to have this change, and performed the following reality check:
```
smartos-build-2(~/smartos-live)[1]% dis -F subprocess /usr/lib/ssh/sshd > /tmp/before
smartos-build-2(~/smartos-live)[0]% dis -F subprocess proto/usr/lib/ssh/sshd > /tmp/after
smartos-build-2(~/smartos-live)[0]% wc -l /tmp/{before,after}
594 /tmp/before
621 /tmp/after
1215 total
smartos-build-2(~/smartos-live)[0]% grep call /tmp/before | wc -l
60
smartos-build-2(~/smartos-live)[0]% grep call /tmp/after | wc -l
63
smartos-build-2(~/smartos-live)[0]% 
```
The additional three `call` instructions should match the three additional function calls from the patch.
> OS-8320 Add CVE-2021-41617 patch to OpenSSH

- libz/Patches/0001-CVE-2022-37434.patch
- node.js/Patches/0004-CVE-2022-37434.patch
- nss-nspr/Patches/CVE-2022-37434.patch
- perl/CVE-2022-37434.patch
- perl/Makefile
- rsync/Patches/0011-CVE-2022-37434.patch
Built successfully, including 0-strap-cache.  Only question is do we need all of these ones patched or not.  My inclination is "yes, for safety," but I can be convinced otherwise.
> OS-8402 patch CVE-2022-37434

- rsync/Patches/0012-allocation-fixes.patch
This is the "patch 3.1.2" approach.  Doing a heavy lift to 3.2.7 may be not as hard as I fear, but this should fix the problem in the short term.
> OS-8426 rsync memory allocation issues

- openssl3/Makefile
Subject says it all.  Test results will end up on ticket. Given it built w/o any patch changes or new symbols, it should be fine, however.
> OS-8488 Update OpenSSL to 3.0.11

- openssh/Patches/0019-PubKeyPlugin-support.patch
Adds support for ED25519 keys and removes per-key-type related code that is no longer used.
This PR is related to TritonDataCenter/illumos-joyent/pull/462, there will be additional PRs (cloudapi, ufds, etc) to enable ED25519 support throughout the Triton stack.
See [OS-8502](https://mnx.atlassian.net/browse/OS-8502?focusedCommentId=123016) for testing notes.
[OS-8502]: https://mnx.atlassian.net/browse/OS-8502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OS-8502 Add support for ED25519 keys, remove unused key checking code

- coreutils/Makefile
Changes were simple enough once moved over to 64-bit builds.  Needs testing.
> OS-8513 Update coreutils in illumos-extra

- openssl3/Makefile
Lucky us, nothing we patch appears to be affected, and no new symbols got added.
> OS-8549 Update OpenSSL to 3.0.14

- openssh/Patches/1003-disable-async-unsafe.patch
> OPENSSH BACKPORT - Disable async-signal-unsafe code in 9.7p1

- socat/Patches/SO_PROTOCOL.patch
Required once we pull illumos#16635 from upstream.
> OS-8562 socat build failure with illumos update #16635

- coreutils/Makefile
- coreutils/Patches/0001-use-new-libs.patch
This is a requirement before accepting https://www.illumos.org/issues/16675 from upstream.
It has been tested locally with a smartos-live build with current `master` of illumos-joyent.  A merged illumos-joyent PLUS this is building locally now.  Also build 713 of  https://jenkins.tritondatacenter.com/job/TritonDataCenter/job/smartos-live/job/master/ is a reproduction of this change plus pre-merge illumos-joyent across all three build types (default, DEBUG, and gcc7).
> OS-8568 coreutils --help invocations of compiled binaries can explode

- gcc10/Makefile
- gcc10/gcc-10.4.0-il-1.tar.gz.sha1
- gcc10/gcc-10.4.0-il-2.tar.gz.sha1
Subject says it all.  Will kick off local build now (1220 US/Eastern).  If successful, should be done in 2hrs, 15mins, and will perform further tests.
> OS-8583 Update gcc10 to very latest illumos snapshot, 10.4.0-il-2

- openssl1x/Patches/0019-Fix-gcc14-warning.patch
Fix declaration (line 9).
Cast over uintptr_t so the structure size check would not be used.
Add check for array index. Signature algorithms start from 1, so idx > 0 is good check.
> OS-8589 openssl1x update for gcc 14

- ntp/Patches/gcc14.patch
ntp has two problems:
1. isc_ioctl() is expecting char * pointer
2. configure pthread_detach() is expecting int, not pointer.
> OS-8595 ntp update for gcc 14

- nss-nspr/Patches/ecperf.patch
- nss-nspr/Patches/jar.patch
- nss-nspr/Patches/pkcs12.patch
- nss-nspr/Patches/sqlite.patch
1. leaking pointer to local variable (set field to NULL to prevent it as our work is done).
2. variable may be used uninitialized (initialize it to NULL).
3. misaligned statements in two locations.
> OS-8590 nss-nspr update for gcc 14

- coreutils/Patches/0002-SmartOS-memset_s-needs-prototype.patch
coreutils is missing declaration for memset_s. And this one is tricky, because, to get the declaration, we need to have:
`#define __STDC_WANT_LIB_EXT1__ 1`
And we do have it. Except we do set it too late, as the string.h header is pulled in in config.h and we are missing the declaration of memset_s.
> OS-8591 coreutils update for gcc 14

- ipmitool/Patches/gcc-14.patch
ipmitool has multiple problems:
- missing prototypes for ipmi_intf_get_max_response_data_size() and ipmi_intf_get_max_request_data_size().
- unused static function fru_area_print_multirec_bloc()
- signed versus unsigned compare
- The if statements which are never true -Wtautological-compare
- string functions are expecting const char * pointer, not unsigned char *
There is also problem about structure with flexible array member used in another structure, but that does emit the warning now, so I did left that one as is.
> OS-8593 ipmitool update for gcc 14

- dialog/Makefile
- dialog/Patches/0001-configure.patch
dialog has configure error with gcc 14; in order to check for ncurses.h, it is using tgoto(), but tgoto() is not declared in ncurses.h at all. Use endwin() instead (as it is done in more recent dialog).
gcc 10 does emit warning, but gcc 14 does count it as an error:
`configure:10782:12: warning: implicit declaration of function 'tgoto' [-Wimplicit-function-declaration]`
> OS-8592 dialog update for gcc 14

- openldap/Patches/gcc14.patch
openldap has two problems:
1. pthread_detach() needs int, not pointer
2. thr_yield() needs thread.h.
> OS-8596 openldap update for gcc 14

- binutils/patches/binutiles_libfl.patch
I got build error while building binutils, proto.strap compiler failed to locate libfl. Investigating the issue, I have determined the binutils does not actually need to be linked against libfl at all. Therefore the fix would be a small patch of [Makefile.am](http://makefile.am/) to prevent libfl to be used to link the binaries.
> OS-8599 binutils does needless link against libfl

- nss-nspr/Patches/ldflags.diff
Local builds now work, Jenkins job 828 on https://jenkins.tritondatacenter.com/job/TritonDataCenter/job/smartos-live/job/master/ is building with this branch as I file this PR.  Will also be updating 1-2 CNs to run further build tests.
All of the above testing notes are also in the ticket.
> OS-8619 nss-nspr internal build tools doesn't use in-proto libraries
